name: Angular CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Lint
      - name: Run Lint
        run: npm run lint

      # Run Unit Tests
      - name: Run Tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      # Build Angular app
      - name: Build Angular App
        run: npm run build -- --configuration=production
